# Formatting
# Name:If_logo_different
Languages:
  Python:
  Go:
  TypeScript:
  Java: OpenJDK
---
TechStack:
  React:
  Nextjs: Next.js
  Express:
  PostgreSQL:
---
DevOps:
  Kubernetes:
  Terraform:
  Docker:
  Ansible:

---
Tools:
  AWS: amazonaws
  Heroku:
  Git:
  Ubuntu:
